### ISSUE TITLE
alpha multiplication with k and K

### ISSUE THREAD

**Issue by lgulich** [anassinator/ilqr#10]
Hi anassinator

First off, thanks a lot for a beautifully written library!

I have noticed that in the following line you multiply alpha with  `(k[i] + K[i]...)`, whereas in the paper eq 12 (as well as in a comment of yours in the lines above) it is mentioned that alpha should only be multiplied with `k[i]`.

https://github.com/anassinator/ilqr/blob/2184c4847fa363c0c67d6c203cf93452981109d8/ilqr/controller.py#L208

Is this done so on purpose?

**Comment by anassinator** [comment]
Yeah, I had issues converging with `alpha` being multiplied with `k[i]` only back then, but I might've inadvertently solved it since, so maybe it should be changed back. You can experiment with both and see what works better for your use case. Technically, multiplying `K[i].dot(xs_new[i] - xs[i])` by `alpha` doesn't really make sense.

**Comment by lgulich** [comment]
Thanks for your response. I experimented with both and the results improved a lot when using the conventional way. Hence why I would recommend to change it back to this way, which is also how it is stated in the paper.

**Comment by anassinator** [comment]
Tested it again too, and it works well enough. Should be fixed in 677ce87
